fieldLayouts:
  e1ad1c2a-97c8-4b64-9d59-41e897a98298:
    tabs:
      -
        elements:
          -
            fieldUid: 21903cb2-5b82-49ea-9766-e120d0951ea3 # Plain Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3ae85e2-d868-435c-9fbb-fa56c7fe0ad3
            warning: null
            width: 100
        name: Default
        uid: 39fa5f70-670b-44cc-a7b2-e7684c2ca914
handle: globals
name: Globals
sortOrder: 0
