dateModified: 1643632348
email:
  fromEmail: andrew@nystudio107.com
  fromName: Craft
  transportType: craft\mail\transportadapters\Sendmail
fs:
  site:
    hasUrls: true
    name: Site
    settings:
      path: '@webroot/assets/site'
    type: craft\fs\Local
    url: '@assetsUrl/assets/site'
meta:
  __names__:
    5c642d7e-b16b-4836-9575-668d75d242e5: Site # Site
    5da841b1-ca0d-46ff-8bb1-04d6c889ac54: English # English
    94b4d5ac-d7ea-4241-a6cb-92b39f482f99: Common # Common
    c4536798-743d-4bf0-9669-192827bfb26c: Blog # Blog
    ec473f07-152f-423b-90df-ac425e6068a1: Spanish # Spanish
    f89601e9-4ba9-4a48-9e99-350aa9914912: plugindev # plugindev
system:
  edition: pro
  live: true
  name: plugindev
  retryDuration: 60
  schemaVersion: 4.0.0
  timeZone: America/New_York
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
